include(GNUInstallDirs)
set(DESTINATION_INCLUDE_DIR "${CMAKE_INSTALL_INCLUDEDIR}/bcos-crypto")
file(COPY hash
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)
file(COPY signature
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)
file(COPY encrypt
    DESTINATION ${DESTINATION_INCLUDE_DIR}
    FILES_MATCHING PATTERN "*.h"
)