set(DESTINATION_INCLUDE_DIR "${CMAKE_INSTALL_INCLUDEDIR}")

install(
        DIRECTORY "bcos-crypto"
        DESTINATION "${DESTINATION_INCLUDE_DIR}"
        FILES_MATCHING PATTERN "*.h"
        PATTERN "${ExcludePattern}" EXCLUDE
)