aux_source_directory(bcos-crypto/hash SRC_LIST)
include_directories(bcos-crypto/hash)
aux_source_directory(bcos-crypto/signature/ SRC_LIST)
include_directories(bcos-crypto/signature)
aux_source_directory(bcos-crypto/signature/secp256k1 SRC_LIST)
include_directories(bcos-crypto/signature/secp256k1)
aux_source_directory(bcos-crypto/signature/sm2 SRC_LIST)
include_directories(bcos-crypto/signature/sm2)
aux_source_directory(bcos-crypto/signature/ed25519 SRC_LIST)
include_directories(bcos-crypto/signature/ed25519)
aux_source_directory(bcos-crypto/encrypt SRC_LIST)
include_directories(bcos-crypto/encrypt)


set(DependLibraries bcos-utilities::bcos-utilities wedpr-crypto::crypto)

if (WIN32)
set(DependLibraries ${DependLibraries} Ws2_32 Wldap32 Crypt32 userenv)
else()
set(DependLibraries ${DependLibraries} pthread dl)
endif()

set(ExcludePattern "bcos-crypto/signature/fastsm2*")
if(SM2_OPTIMIZE)
    hunter_add_package(OpenSSL)
    find_package(OpenSSL REQUIRED)
    aux_source_directory(bcos-crypto/signature/fastsm2 SRC_LIST)
    include_directories(bcos-crypto/signature/fastsm2)
    set(DependLibraries OpenSSL::Crypto ${DependLibraries})
    set(ExcludePattern "")
endif()