aux_source_directory(./hash SRC_LIST)
include_directories(./hash)
aux_source_directory(./signature/ SRC_LIST)
include_directories(./signature)
aux_source_directory(./signature/secp256k1 SRC_LIST)
include_directories(./signature/secp256k1)
aux_source_directory(./signature/sm2 SRC_LIST)
include_directories(./signature/sm2)
aux_source_directory(./signature/ed25519 SRC_LIST)
include_directories(./signature/ed25519)
aux_source_directory(./encrypt SRC_LIST)
include_directories(./encrypt)


set(DependLibraries bcos-utilities::bcos-utilities wedpr-crypto::crypto)

if (WIN32)
set(DependLibraries ${DependLibraries} Ws2_32 Wldap32 Crypt32 userenv)
else()
set(DependLibraries ${DependLibraries} pthread dl)
endif()

set(ExcludePattern "signature/fastsm2*")
if(SM2_OPTIMIZE)
    hunter_add_package(OpenSSL)
    find_package(OpenSSL REQUIRED)
    aux_source_directory(./signature/fastsm2 SRC_LIST)
    include_directories(./signature/fastsm2)
    set(DependLibraries OpenSSL::Crypto ${DependLibraries})
    set(ExcludePattern "")
endif()