function(install_dep dep_name dep_version)
    list(LENGTH ARGN components)
    message("Require ${dep_name} ${dep_version} for ${components} components: ${ARGN}")
    set(all_FOUND true)

    if(NOT FORCE_HUNTER_DEP)
        if(${components} GREATER 0)
            find_package(${dep_name} ${dep_version} COMPONENTS ${ARGN})
            foreach(package ${ARGN})
                string(TOUPPER ${package} upper_package)
                message("Package ${dep_name}_${package}_FOUND is ${${dep_name}_${upper_package}_FOUND}")

                if(NOT ${${dep_name}_${upper_package}_FOUND})
                    set(all_FOUND false)
                endif()
            endforeach()
        else()
            find_package(${dep_name} ${dep_version})
        endif()
    endif()

    if(NOT ${${dep_name}_FOUND})
        set(all_FOUND false)
    endif()

    if(NOT ${all_FOUND} OR ${FORCE_HUNTER_DEP})
        message("Not found ${dep_name} all local dependency! Use hunter to install ${dep_name}")
        if(${components} GREATER 0)
            hunter_add_package(${dep_name} COMPONENTS ${ARGN})
            find_package(${dep_name} ${dep_version} REQUIRED COMPONENTS ${ARGN})
        else()
            hunter_add_package(${dep_name})
            find_package(${dep_name} ${dep_version} REQUIRED)
        endif()
    endif()
endfunction(install_dep)