macro(install_dep dep_name dep_version)
    list(LENGTH ARGN ARGNS)
    if(NOT FORCE_HUNTER_DEP)
        if(${ARGNS} GREATER 0)
            find_package(${dep_name} ${dep_version} REQUIRED)
        else()
            find_package(${dep_name} ${dep_version} REQUIRED COMPONENTS ${ARGN})
        endif()
    endif()

    if(NOT ${dep_name}_FOUND OR FORCE_HUNTER_DEP)
        message("Not found local dependency ${dep_components}! Use hunter")
        if(${ARGNS} GREATER 0)
            hunter_add_package(${dep_name} REQUIRED)
            find_package(${dep_name} ${dep_version} REQUIRED)
        else()
            hunter_add_package(${dep_name} COMPONENTS ${ARGN})
            find_package(${dep_name} ${dep_version} REQUIRED COMPONENTS ${ARGN})
        endif()
    endif()
endmacro(install_dep)