name: FISCO-BCOS GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]
jobs:
  build_with_vcpkg:
    name: build_with_vcpkg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-2019,macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }
      - name: Prepare windows msbuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      - name: Prepare linux build tool
        if: runner.os == 'Linux'
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
      - name: Configure for macOS
        if: runner.os == 'macOS'
        run:
          mkdir -p build && cd build && CC="$(brew --prefix llvm)/bin/clang" CXX="$(brew --prefix llvm)/bin/clang++" cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DHUNTER_ENABLED=OFF -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
      - name: Configure for linux and windows
        if: runner.os != 'macOS'
        run:
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DHUNTER_ENABLED=OFF -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake ../
      - name: Compile
        run: 
          cd build && cmake --build . --parallel
      - name: Test
        if: runner.os != 'Windows'
        run:
          cd build && CTEST_OUTPUT_ON_FAILURE=TRUE ctest